# This workflow gathers the pipelines which will be executed on event bases.

name: Security
on:
  push:
    branches:
      - devops/blackduck
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: setup_java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: blackduck
        uses: synopsys-sig/synopsys-action@v1.1.0
        with:
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_scan_full: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          blackduck_automation_fixpr: true
          blackduck_scan_failure_severities: "ALL"
