name: Blackduck
on:
  workflow_call:
    inputs:
      version_file:
        description: 'Version file'
        required: true
        type: string
      runner:
        description: 'Runner name'
        required: true
        type: string

env:
  # Blackduck
  BLACKDUCK_API_TOKEN: ${{ secrets.ORG_BLACKDUCK_API_TOKEN }}
  BLACKDUCK_URL: ${{ secrets.ORG_BLACKDUCK_URL }}
  DETECT_PROJECT_NAME: ${{ secrets.DETECT_PROJECT_NAME }}
  LOGGING_LEVEL_COM_SYNOPSYS_INTEGRATION: DEBUG

jobs:
  scan:
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up NodeJS environment
        uses: actions/setup-node@v4
      - name: Detect version
        id: detect_version
        run: |
          echo "version_name=$(cat ${{github.workspace}}/${{ inputs.version_file }} | jq -r .version)" >> $GITHUB_OUTPUT
      - name: Synopsys Scan mode intelligent
        if: ${{ github.event_name == 'push' }}
        uses: synopsys-sig/synopsys-action@v1.6.0
        with:
          github_token: ${{ secrets.ORG_CI_GH_TOKEN }}
          blackduck_url: ${{ secrets.ORG_BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.ORG_BLACKDUCK_API_TOKEN }}
          blackduck_scan_full: true
        # TODO: uncomment the following if pull request creation works
        #  blackduck_fixpr_enabled: true
        #  blackduck_fixpr_maxCount: 5
        #  blackduck_fixpr_filter_severities: 'CRITICAL,HIGH,MEDIUM,LOW'
        #  blackduck_fixpr_useUpgradeGuidance: 'SHORT_TERM,LONG_TERM'
        #  blackduck_automation_fixpr: true
        env:
          DETECT_PROJECT_VERSION_NAME: ${{ steps.detect_version.outputs.version_name }}
      # Perform rapid scan for pull request and dependentbot jobs
      - name: Synopsys Scan mode rapid
        if: ${{ github.event_name != 'push' }}
        uses: synopsys-sig/synopsys-action@v1.6.0
        with:
          github_token: ${{ secrets.ORG_CI_GH_TOKEN }}
          blackduck_url: ${{ secrets.ORG_BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.ORG_BLACKDUCK_API_TOKEN }}
          blackduck_scan_full: false
          blackduck_prComment_enabled: true
        env:
          DETECT_PROJECT_VERSION_NAME: ${{ steps.detect_version.outputs.version_name }}
