name: Chromatic

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner name'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install package dependencies
        run: npm install
      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
