name: Linting

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner name'
        required: true
        type: string

jobs:
  lint:
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up NodeJS environment
        uses: actions/setup-node@v4
      - name: Install package dependencies
        run: npm install
      - name: Check linting and formatting
        run: npm run lint
