name: Unit Tests

on:
  workflow_call:
    inputs:
      use_private_registry:
        description: 'Use private npm registry'
        required: true
        type: boolean
      runner:
        description: 'Runner name'
        required: true
        type: string

jobs:
  unit-tests:
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NodeJS environment without registry
        if : ${{ inputs.use_private_registry == false }}
        uses: actions/setup-node@v3

      - name: Set up NodeJS environment with registry
        if : ${{ inputs.use_private_registry == true }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@DicoAuto'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_CI_GH_TOKEN }}

      - name: Install package dependencies without registry
        if : ${{ inputs.use_private_registry == false }}
        run: npm install

      - name: Install package dependencies with registry
        if : ${{ inputs.use_private_registry == true }}
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_CI_GH_TOKEN }}

      - name: Execute test cases
        run: npm run test

      - name: Execute test coverage
        run: npm run test:coverage

      - name: Archive coverage
        uses: actions/upload-artifact@v3
        with:
          # Upload entire repository
          name: coverage-${{ github.run_id }}
          path: ${{github.workspace}}/coverage/
