# This workflow gathers the pipelines which will be executed on event bases.

name: workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # build
  build-prod:
    if: |
      contains(fromJSON('["push", "pull_request"]'), github.event_name) ||
      (contains(fromJSON('["main"]'), github.base_ref) ||
       contains(fromJSON('["main"]'), github.ref_name))
    uses: ./.github/workflows/web-build.yaml
    secrets: inherit
    with:
      use_private_registry: false
      runner: ubuntu-latest

  # lint
  linting:
    if: |
      contains(fromJSON('["push", "pull_request"]'), github.event_name) ||
      (contains(fromJSON('["main"]'), github.base_ref) ||
       contains(fromJSON('["main"]'), github.ref_name))
    uses: ./.github/workflows/web-lint.yaml
    secrets: inherit
    with:
      use_private_registry: false
      runner: ubuntu-latest

  # unit-tests
  tests:
    if: |
      contains(fromJSON('["push", "pull_request"]'), github.event_name) ||
      (contains(fromJSON('["main"]'), github.base_ref) ||
       contains(fromJSON('["main"]'), github.ref_name))
    uses: ./.github/workflows/web-test.yaml
    secrets: inherit
    with:
      use_private_registry: false
      runner: ubuntu-latest

  # sonarqube
  sonarqube:
    needs: [build-prod, linting, tests]
    if: |
      contains(fromJSON('["push", "pull_request"]'), github.event_name) ||
      (contains(fromJSON('["main"]'), github.base_ref) ||
       contains(fromJSON('["main"]'), github.ref_name))
    uses: ./.github/workflows/web-sonarqube.yaml
    secrets: inherit
    with:
      verbose: false
      runner: ubuntu-latest

  # deploy docs
  gh-pages:
    if: |
      contains(fromJSON('["push"]'), github.event_name) &&
      contains(fromJSON('["main"]'), github.ref_name)
    uses: ./.github/workflows/web-docs.yaml
    secrets: inherit
    with:
      runner: ubuntu-latest

  # deploy chromatic
  chromatic:
    needs: [build-prod, linting, tests]
    if: |
      contains(fromJSON('["push", "pull_request"]'), github.event_name) ||
      (contains(fromJSON('["main"]'), github.base_ref) ||
      contains(fromJSON('["main"]'), github.ref_name))
    uses: ./.github/workflows/web-chromatic.yaml
    secrets: inherit
    with:
      runner: ubuntu-latest

  # scan security & license compliance
  blackduck:
    if: |
      contains(fromJSON('["push", "pull_request"]'), github.event_name) ||
      (contains(fromJSON('["main"]'), github.base_ref) ||
      contains(fromJSON('["main"]'), github.ref_name))
    uses: ./.github/workflows/web-blackduck.yaml
    secrets: inherit
    with:
      version_file: package.json
      runner: ubuntu-latest