# This workflow gathers the pipelines which will be executed on event bases.

name: workflows

on:  
  push:
  pull_request:

jobs:

  # build
  build-prod:
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'push' && github.ref_name == 'main'
    uses: DicoAuto/actions/.github/workflows/web-build.yaml@feature/web_launch_sonarqube
    secrets: inherit
    with:
      runner: ubuntu-latest

  # lint
  code-smells:
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'push' && github.ref_name == 'main'
    uses: DicoAuto/actions/.github/workflows/web-lint.yaml@feature/web_launch_sonarqube
    secrets: inherit
    with:
      runner: ubuntu-latest

  # unit-tests
  tests:
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'push' && github.ref_name == 'main'
    uses: DicoAuto/actions/.github/workflows/web-test.yaml@feature/web_launch_sonarqube
    secrets: inherit
    with:
      runner: ubuntu-latest

  # sonarqube
  sonarqube:
    needs: [tests]
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'push' && github.ref_name == 'main'
    uses: DicoAuto/actions/.github/workflows/web-sonarqube.yaml@feature/web_launch_sonarqube
    secrets: inherit
    with:
      ref_branch: 'main'
      verbose: true
      runner: ubuntu-latest

  # deploy docs
  gh-pages:
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: DicoAuto/actions/.github/workflows/web-docs.yaml@feature/web_launch_sonarqube
    secrets: inherit
    with:
      runner: ubuntu-latest

  # deploy chromatic
  chromatic:
    if: github.event_name == 'push'
    uses: DicoAuto/actions/.github/workflows/web-chromatic.yaml@feature/web_launch_sonarqube
    secrets: inherit
    with:
      runner: ubuntu-latest
